package ejemplo03.dominio;
// Generated 19-feb-2019 10:11:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private Integer idMunicipio;
     private Provincia provincia;
     private int codMunicipio;
     private Set<Biblioteca> bibliotecas = new HashSet<Biblioteca>(0);

    public Municipio() {
    }

	
    public Municipio(Provincia provincia, int codMunicipio) {
        this.provincia = provincia;
        this.codMunicipio = codMunicipio;
    }
    public Municipio(Provincia provincia, int codMunicipio, Set<Biblioteca> bibliotecas) {
       this.provincia = provincia;
       this.codMunicipio = codMunicipio;
       this.bibliotecas = bibliotecas;
    }
   
    public Integer getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(Integer idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public int getCodMunicipio() {
        return this.codMunicipio;
    }
    
    public void setCodMunicipio(int codMunicipio) {
        this.codMunicipio = codMunicipio;
    }
    public Set<Biblioteca> getBibliotecas() {
        return this.bibliotecas;
    }
    
    public void setBibliotecas(Set<Biblioteca> bibliotecas) {
        this.bibliotecas = bibliotecas;
    }




}


