package ejemplo03.dominio;
// Generated 19-feb-2019 10:11:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private Integer idProvincia;
     private int codProvincia;
     private String nomProvincia;
     private Set<Municipio> municipios = new HashSet<Municipio>(0);

    public Provincia() {
    }

	
    public Provincia(int codProvincia, String nomProvincia) {
        this.codProvincia = codProvincia;
        this.nomProvincia = nomProvincia;
    }
    public Provincia(int codProvincia, String nomProvincia, Set<Municipio> municipios) {
       this.codProvincia = codProvincia;
       this.nomProvincia = nomProvincia;
       this.municipios = municipios;
    }
   
    public Integer getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(Integer idProvincia) {
        this.idProvincia = idProvincia;
    }
    public int getCodProvincia() {
        return this.codProvincia;
    }
    
    public void setCodProvincia(int codProvincia) {
        this.codProvincia = codProvincia;
    }
    public String getNomProvincia() {
        return this.nomProvincia;
    }
    
    public void setNomProvincia(String nomProvincia) {
        this.nomProvincia = nomProvincia;
    }
    public Set<Municipio> getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Set<Municipio> municipios) {
        this.municipios = municipios;
    }




}


